let express = require('express')
let router = express.Router()
let uploadProfilePicture = require('../helpers/uploadProfilePicture')
let verifyToken = require('../helpers/verifyToken')
const { userController } = require('../controllers')

router.get('/users', verifyToken, userController.getUsers)
router.get('/users/:id', verifyToken, userController.getUsers)
router.post('/users', verifyToken, userController.createUser)
router.patch('/users/:id', verifyToken, userController.editWithoutProfilePicture)
router.patch('/users_picture/:id', verifyToken, uploadProfilePicture.single('browse_file'), userController.editWithProfilePicture)
router.get('/login', userController.loginUser)
router.post('/send_verification_link', userController.sendVerificationLink)
router.get('/check_verification_link', userController.checkVerificationLink)
router.patch('/verify_user', verifyToken, userController.verifyUser)
router.post('/send_password_link', userController.sendPasswordLink)
router.get('/check_password_link', userController.checkPasswordLink)
router.patch('/reset_password', verifyToken, userController.resetPassword)

module.exports = router